# docker/api/Dockerfile.prod

# Build Stage
FROM golang:1.23-alpine AS builder

WORKDIR /app

# Copy go.mod and go.sum from the build context
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/server

# Run Stage
FROM alpine:latest

WORKDIR /root/

# Copy the built binary
COPY --from=builder /app/main .

# Expose port
EXPOSE 8080

# Run the executable
CMD ["./main"]
