# docker-compose.yaml

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: ../docker/api/Dockerfile.prod
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      MISTRAL_API_URL: ${MISTRAL_API_URL}
      MISTRAL_API_MODEL: ${MISTRAL_API_MODEL}
    networks:
      - app-network


  web:
    build:
      context: ./web
      dockerfile: ./docker/web/Dockerfile.prod
      args:
        API_BASE_URL: "http://${API_HOST:-api}:${API_PORT:-8080}"
    ports:
      - '80:80'
    depends_on:
      - api
    networks:
      - app-network


volumes:
  db_data:

networks:
  app-network:
