# docker-compose.dev.yaml

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - '5432:5432'

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile.dev
    volumes:
      - ./api:/app
      - ./.air.toml:/app/.air.toml
    ports:
      - '8080:8080'
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_SSL_MODE: ${POSTGRES_SSL_MODE}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      MISTRAL_API_URL: ${MISTRAL_API_URL}
      MISTRAL_API_MODEL: ${MISTRAL_API_MODEL}
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
